### ISSUE TITLE
Break up with core and portal modules

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/icebox#161]
Once we have SPA running, the next step is to completely break up with the Core and Portal modules. The goal should be that the frontend only communicates with backend by web API.

- [x] DOWNLOAD DATA form is still using QueryBuilder cBioPortal/cbioportal#5189
- [ ] Any other dependency to QueryBuilder
- [ ] List the servlets that we are still using in frontend
  - [ ] network.do cBioPortal/cbioportal#4652
  - [ ] svg2pdf
  - [ ] ...
- [ ] Any other dependencies to Core?
  - [ ] https://github.com/cBioPortal/cbioportal/pull/5722
- [ ] Any dependencies to Portal module?
  - [x] Refactor OncoPrinter cBioPortal/cbioportal#5093 
  - [ ] move all docs to /docs #768
