### ISSUE TITLE
Group comparison - Phase 2

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/icebox#219]
- [x] Methylation tab cBioPortal/cbioportal#7683
- [ ] Should we support continuous CNA data?
- [x] Support patient level enrichments analysis cBioPortal/cbioportal#4637 
- [x] treat overlapping part as a separate group cBioPortal/cbioportal#5803
- [x] Integrate the Comparison component with Results page cBioPortal/cbioportal#5802
- [x] Comparison tab in Results: allow group samples by gene/track cBioPortal/cbioportal#5804 
- [ ] Enrichments test for oncogenic mutations/cnas/fusions only
- [ ] Enrichments test for pathways
- [x] Enrichments test for mutational signatures
