### ISSUE TITLE
extend generic assay to support categorical data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/icebox#222]
- [x] rfc https://github.com/cbioportal/cbioportal/issues/7920
- [x] backend support https://github.com/cBioPortal/cbioportal/issues/7932
- [x] OncoPrint track - similar to clinical track https://github.com/cBioPortal/cbioportal/issues/7934 https://github.com/cBioPortal/cbioportal/issues/8313
- [x] Plots tab https://github.com/cBioPortal/cbioportal/issues/7935
- [x] Download tab https://github.com/cBioPortal/cbioportal/issues/7936
- [x] Study view: load pie chart https://github.com/cBioPortal/cbioportal/issues/7938
- [ ] Study view: frequency count table for Binary data https://github.com/cBioPortal/cbioportal/issues/7940
- [x] Comparison: fisher's exact test for Binary data and chi-square test for Categorical data https://github.com/cBioPortal/cbioportal/issues/11312
