### ISSUE TITLE
Improving generic assay features phase 2

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/icebox#251]
- [ ] generic assay for discrete data cBioPortal/icebox#222
- [x] add generic assay data to study view cBioPortal/cbioportal#7657
- [ ] add generic assay data to Coexpression cBioPortal/icebox#139 (less important)
