### ISSUE TITLE
Arbitrary categorical vs numerical plots in study view

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/icebox#307]
Part of https://github.com/cBioPortal/icebox/issues/223

Box/Violin plot table

1st iteration:
- [x] Two options (can be overlaid) https://github.com/cBioPortal/cbioportal/issues/9077
  - Boxplot
  - Violin plot
- [x] tooltip for outliers https://github.com/cBioPortal/cbioportal/issues/9078
- [x] axes https://github.com/cBioPortal/cbioportal/issues/9079
- [x] study view filtering https://github.com/cBioPortal/cbioportal/issues/9080
- [x] saving to user settings https://github.com/cBioPortal/cbioportal/issues/9081
- [x] #samples column should be right justified
- [x] sort by columns
- [x] respond to resizing https://github.com/cBioPortal/cbioportal/issues/9082
- [x] option to show additional columns, e.g. median https://github.com/cBioPortal/cbioportal/issues/9082
- [x] Sometimes grid lines get bunched up at the top
- [x] resizing categorical column width
- [ ] change violin plot colors (maybe light gray similar to boxplot?)
- [ ] Dont filter numerical, just highlight the filter range. (https://github.com/cBioPortal/cbioportal-frontend/pull/4216)
- [ ] Filtering seems to mess up the boxes (maybe moot due to previous point)
- [x] Make center horizontal boxplot line thinner/fainter and add whiskers

2nd iteration:
- [ ] scatter dots
- [ ] filter by columns (similar to Mutations table)
- [ ] export as pdf
- [ ] data download
- [ ] Show full category names on mouseover if truncated
- [ ] option to swap x & y?
- [ ] 2-dimensional data availability for dropdowns in attribute selectors
