### ISSUE TITLE
Public Release of API

### ISSUE THREAD

**Issue by inodb** [cBioPortal/icebox#564]
Before the official 1.0 release of the API we should do the following:

- [x] Create User Friendly API Documentation. Current API auto generated docs are not easy to read. Give general overview of API (#7469)
- [x] Deprecation message (https://github.com/cBioPortal/cbioportal/issues/2967)
- [x] Go over all API endpoints and check consistency
    - [ ] In particular generic assay endpoints: https://github.com/cBioPortal/cbioportal/issues/6955, https://github.com/cBioPortal/icebox/issues/200
- [ ] Address issues identified while going over all endpoints: https://docs.google.com/document/d/1KC07Rl_oD6jYUyYahv4UrS-GIuLWnr4biaWop826U1Y
- [x] Only use public API endpoints (https://github.com/cBioPortal/cbioportal/issues/3289)
- [ ] Jupyter Notebooks
    - [ ] Python (can use a lot from https://github.com/mskcc/cbsp-hackathon)
    - [ ] R (Deprecate cgdsr in favor of cBioPortalData and rapiclient if endpoint is not supported)
- [ ] Document other clients
    - [x] JavaScript (fix https://github.com/cBioPortal/cbioportal/issues/6716)
    - [ ] Java
- [x] Remove A/B/C etc from endpoint names (find another way to sort endpoints)
- [ ] Styling/navigation of API page. Should it live inside docs.cbioportal.org and/or inside cBioPortal shell, or should we expand swagger page with more custom look (related: https://github.com/cBioPortal/cbioportal/issues/2969)
- [ ] Move treatments to internal (https://github.com/cBioPortal/icebox/issues/561)
- [ ] Move Clinical_Events endpoint to default (https://github.com/cBioPortal/icebox/issues/562)
- [ ] Move Structural_Variants endpoint to default (https://github.com/cBioPortal/icebox/issues/563)
- [ ] Add more notebooks to codebook repo (http://github.com/cbioportal/codebook)
- [ ] Describe API at a higher level. Explain what molecular profiles are, generic assays, gene panels, etc
- [ ] Decide how we manage versioning of the API and document the process of endpoint updates (https://github.com/cBioPortal/icebox/issues/267)
- [ ] Swagger issues: https://github.com/cBioPortal/cbioportal/issues/9414
- [ ] Should we expose the Session endpoint?

For auth enabled portals:

- [x] For each of the client docs include how to connect to an authenticated portal

Would be nice (requires db migration):

- [x] Remove Category from Sample List API (https://github.com/cBioPortal/cbioportal/issues/4933). (Decided not to follow up on because of potential future case list changes)
